services:
  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    build: .
    profiles: ["main"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      HF_HOME: /app/hf_cache
      HF_XET_HIGH_PERFORMANCE: 1
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      MISTRAL_TOKEN: ${MISTRAL_TOKEN}
      MISTRAL_MODEL_NAME: ${MISTRAL_MODEL_NAME}
    volumes:
      - chroma_data:/app/chroma_db_folder
      - hf_cache:/app/hf_cache
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]

  bot:
    build: .
    profiles: ["main"]
    depends_on:
      - api
    environment:
      TG_TOKEN: ${TG_TOKEN}
      API_URL: "http://api:8000/api/chat"
    command: ["python", "bot.py"]

  init_db:
    build: .
    profiles: ["init"]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
      HF_XET_HIGH_PERFORMANCE: 1
      HF_HOME: /app/hf_cache
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - chroma_data:/app/chroma_db_folder
      - hf_cache:/app/hf_cache
    command: ["python", "init_db.py"]

volumes:
  pgdata:
  chroma_data:
  hf_cache:
